<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>DNA.Email.API</RootNamespace>
    <AssemblyName>DNA.Email.API</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DNA.Email.Core\DNA.Email.Core.csproj" />
  </ItemGroup>

</Project>
